name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-fedora:
    strategy:
      matrix:
        fedora-version: [latest, rawhide]
        compiler: [gcc, clang]

    runs-on: ubuntu-latest
    container: fedora:${{matrix.fedora-version}}

    steps:
    - name: Install packages
      run: dnf -y --setopt=install_weak_deps=False install git cmake ninja-build qt5-qtbase-devel qt5-qtx11extras-devel qt5-linguist kf5-kwidgetsaddons-devel kf5-kwindowsystem-devel gettext ${{ matrix.compiler == 'gcc' && 'gcc-c++' || 'clang' }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Tremotesf
      uses: equeim/action-cmake-build@v5.2
      with:
        cmake-arguments: --preset default -D CMAKE_CXX_COMPILER=${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
        install: true

  build-ubuntu:
    strategy:
      matrix:
        ubuntu-version: [latest, rolling]
        compiler: [gcc, clang]

    runs-on: ubuntu-latest
    container: ubuntu:${{matrix.ubuntu-version}}

    steps:
    - name: Install packages
      run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends --assume-yes install ca-certificates git cmake ninja-build qtbase5-dev libqt5x11extras5-dev qttools5-dev libkf5widgetsaddons-dev libkf5windowsystem-dev gettext ${{ matrix.compiler == 'gcc' && 'g++' || 'clang' }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Tremotesf
      uses: equeim/action-cmake-build@v5.2
      with:
        # Can't use presets on older Ubuntu version
        cmake-arguments: -D CMAKE_CXX_COMPILER=${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
        install: true

  build-windows:
    uses: ./.github/workflows/build-windows.yml
